title: Davor Kondic # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Welcome to my Projects Portfolio site!
  I built this site personally with Github Pages to
  showcase some of my personal projects and my full stack data analytics and data engineering skills.
  Here you will find the front end or user interface of each project and will be able to interact and use it
  directly within the site. For more information like source code or dashboard workbooks please visit one of my
  Tableau, Github, or Huggingface repos listed below.
  Hope you enjoy using them as much I as did building them!
  <br><br>
  <a href="https://public.tableau.com/app/profile/davor.kondic/vizzes">View my Tableau Public Profile</a>
  <br><br>
  <a href="https://www.linkedin.com/in/davor-kondic-54576886/">View my LinkedIn Profile</a>
  <br><br>
  <a href="https://huggingface.co/dkondic">View my HuggingFace Profile.</a>

theme: jekyll-theme-minimal
google-site-verification: jE1LhpjTml2Dgg9YDJQhQv0HkhutqsSzY0LoVNZFx-0
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
